### ISSUE TITLE
Should work on Node.js / server-side

### ISSUE THREAD

**Issue by wyqydsyq** [appcues/snabbdom-virtualize#16]
I'm building an isomorphic app using Cycle.js, everything works great so far except I'm trying to append a string of webpack-generated HTML to my `head` snabbdom tag.

Webpack is generating a plain HTML string of `<link>` tags for favicons, I want to virtualize this string so I can add those tags to the `head` element in my snabbdom VTree.

When trying to do this on the server-side, I get the error "document is not defined", because `snabbdom-virtualize` seems to use `document` for automatically parsing HTML entities in `./src/utils.js`, and `document` and `window` globals don't exist in a Node.js context.

This could be remedied by `snabbdom-virtualize` transparently using something like https://github.com/tmpvar/jsdom when `window` and/or `document` are undefined.

**Comment by rayd** [comment]
This should now be fixed in 0.6.0! Thanks for the help on this @wyqydsyq!
