### ISSUE TITLE
Doesn't virtualize HTML entities

### ISSUE THREAD

**Issue by mightyiam** [appcues/snabbdom-virtualize#23]
https://developer.mozilla.org/en-US/docs/Glossary/Entity

When parsed through the browser's parser, HTML entities are probably converted into unicode internally, right?

For example, try with the following character: `’` (code point 2019).

https://www.npmjs.com/search?q=html%20entities&page=1&ranking=optimal

**Comment by rayd** [comment]
This should be resolved by #28. Thanks for the report!
